# Generated by Django 4.2 on 2024-01-04 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_auto_20210927_2302"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
